Document: mplayerd
Title: Debian mplayerd Manual
Author: <insert document author here>
Abstract: This manual describes what mplayerd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mplayerd/mplayerd.sgml.gz

Format: postscript
Files: /usr/share/doc/mplayerd/mplayerd.ps.gz

Format: text
Files: /usr/share/doc/mplayerd/mplayerd.text.gz

Format: HTML
Index: /usr/share/doc/mplayerd/html/index.html
Files: /usr/share/doc/mplayerd/html/*.html
